### ISSUE TITLE
React 17

### ISSUE THREAD

**Issue by linonetwo** [wubostc/virtualized-table-for-antd#77]
I got this after upgrade to React 17

```
Uncaught Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.
    at resolveDispatcher (index.js:272434)
    at useMemo (index.js:272489)
    at Module.useVT (index.js:270198)
    at VirtualTable (index.js:274391)
    at renderWithHooks (index.js:242734)
    at mountIndeterminateComponent (index.js:245560)
    at beginWork (index.js:246798)
    at HTMLUnknownElement.callCallback (index.js:231694)
    at Object.invokeGuardedCallbackDev (index.js:231743)
    at invokeGuardedCallback (index.js:231805)

index.js:247834 The above error occurred in the <VirtualTable> component:

    at VirtualTable (http://localhost:3762/%E7%BD%91%E7%9B%9F%E4%BB%A3%E7%90%86%E5%B7%A5%E5%85%B7/index.js:274390:26)
    at div
    at ProxyListPage (http://localhost:3762/%E7%BD%91%E7%9B%9F%E4%BB%A3%E7%90%86%E5%B7%A5%E5%85%B7/index.js:274080:9)
    at inject-with-requestStore(ProxyListPage) (http://localhost:3762/%E7%BD%91%E7%9B%9F%E4%BB%A3%E7%90%86%E5%B7%A5%E5%85%B7/index.js:148449:64)
    at component
    at div
    at App (http://localhost:3762/%E7%BD%91%E7%9B%9F%E4%BB%A3%E7%90%86%E5%B7%A5%E5%85%B7/index.js:273833:11)
    at component
    at RouterContext (http://localhost:3762/%E7%BD%91%E7%9B%9F%E4%BB%A3%E7%90%86%E5%B7%A5%E5%85%B7/index.js:103110:37)
    at Router (http://localhost:3762/%E7%BD%91%E7%9B%9F%E4%BB%A3%E7%90%86%E5%B7%A5%E5%85%B7/index.js:103110:37)
    at MobXProvider (http://localhost:3762/%E7%BD%91%E7%9B%9F%E4%BB%A3%E7%90%86%E5%B7%A5%E5%85%B7/index.js:148418:24)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
```

**Comment by thekennysong** [comment]
+1

**Comment by wubostc** [comment]
ok

**Comment by wubostc** [comment]
Published

**Comment by linonetwo** [comment]
谢谢你的持续支持！

**Comment by wubostc** [comment]
published!
